#### Loading Iris data into scikit-learn

In [1]:
# we are loading load_iris fun. from sklearn.datasets module
from sklearn.datasets import load_iris

In [2]:
# create object to load iris data
iris_data = load_iris()

In [3]:
type(iris_data)

sklearn.datasets.base.Bunch

In [4]:
print (iris_data.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [8]:
# what are the features avialable in the data?
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
# what is the target for our analysis?
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# and target names are ?
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [12]:
# check the datatypes of both features and response variable
print (type(iris_data.data), type(iris_data.target))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [13]:
# now what about their shapes?
# 150 - no. of rows (observations) and 4 - no. of columns(features)
iris_data.data.shape

(150, 4)

In [15]:
# should be equal to number of observations or row
iris_data.target.shape

(150,)

In [5]:
# let's store feature variable and response variable in two variables -X (matrix) and y(vector) respectively.
X = iris_data.data
y = iris_data.target

### Model Building Steps

#### STEP 1 : Identify the scikit-learn module you are going to use.

In [6]:
### since we are dealing with classification problem, let's explore k-nearest neighbors model
from sklearn.neighbors import KNeighborsClassifier

#### STEP2 : Let's instantiate the model

In [7]:
### the model is using single neighbors' attributes to identify unknown class.
model = KNeighborsClassifier(n_neighbors=1)

In [8]:
### let us observe the model that we created above.

print ( model )

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


#### STEP3 : Model Training

In [9]:
### here, we are building relationship between X and y varialbes

model.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

#### STEP4 : Prediction

In [10]:
### Suppose, we have new unknown data with features (3,4,5,1), what will be it's class? Let's predict.
### response value predicts to be '2'.i.e 
unknown_class = [3,4,5,1]
model.predict(unknown_class)

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [13]:
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

i.e '2' is virginica.

### Let us use another classification model : LogisticRegression

In [14]:
from sklearn.linear_model import LogisticRegression
# initiate
log_model = LogisticRegression()
#train the model.
log_model.fit(X,y)
#predict
log_model.predict(unknown_class)

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])